--DROP DATABASE SNOWFLAKE_PROJECT;
DROP DATABASE SNOWFLAKE_BRONZE;
DROP DATABASE SNOWFLAKE_SILVER;

CREATE DATABASE SNOWFLAKE_BRONZE;
USE DATABASE SNOWFLAKE_BRONZE;
CREATE SCHEMA SAS;
USE SCHEMA SAS;
CREATE OR REPLACE TABLE BRONZE( ID INTEGER , DATE TIMESTAMP, JSON_DATA VARCHAR );
SELECT * FROM SNOWFLAKE_BRONZE.SAS.BRONZE;


CREATE DATABASE SNOWFLAKE_SILVER;
USE DATABASE SNOWFLAKE_SILVER;
CREATE SCHEMA SAS;
USE SCHEMA SAS;
CREATE OR REPLACE TABLE SILVER( ID INTEGER , DATE TIMESTAMP, JSON_DATA VARCHAR ); 
SELECT * FROM SILVER;
--SHOW TABLES; 
--SHOW WAREHOUSES;
--CREATE WAREHOUSE IF NOT EXISTS SAMPLE_WH WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND=1200;  